MODULE EXP_VAR
USE READ_MISC
IMPLICIT NONE
TYPE EXP_VAR_IN
INTEGER :: INC_TMP = EXP_TMP, INC_CO = EXP_CO, INC_CO2 = EXP_CO2, INC_O2 = EXP_O2, INC_HCN = EXP_HCN, INC_VIS = EXP_VIS, INC_RAD = EXP_RAD
END TYPE EXP_VAR_IN
TYPE EXP_VAR_OUT
INTEGER :: n_dead_tmp = 0, n_dead_co = 0, n_dead_co2 = 0, n_dead_o2 = 0, n_dead_hcn = 0, n_dead_vis = 0, n_dead_rad = 0
END TYPE EXP_VAR_OUT
END MODULE EXP_VAR
